from langchain.tools import tool
import json
import requests


# ==================== SERVICE 1: WEATHER API ====================
@tool
def get_weather(location: str) -> str:
    """
    Get current weather for a specific location.
    Uses the Open-Meteo Weather API.
    
    Args:
        location: City or location name (e.g., "London", "New York")
    
    Returns:
        Weather information including temperature, conditions, humidity, and wind speed
    """
    try:
        if not location or location.lower() in ["weather"]:
            location = "New York"  # Default location
        
        # Use Open-Meteo Geocoding API to get coordinates
        geo_url = "https://geocoding-api.open-meteo.com/v1/search"
        geo_params = {"name": location, "count": 1, "language": "en", "format": "json"}
        
        geo_response = requests.get(geo_url, params=geo_params, timeout=5)
        geo_data = geo_response.json()
        
        if not geo_data.get("results"):
            return f"I couldn't find weather information for '{location}'. Try another location."
        
        # Get coordinates
        result = geo_data["results"][0]
        latitude = result["latitude"]
        longitude = result["longitude"]
        name = result.get("name", location)
        country = result.get("country", "")
        
        # Get weather data
        weather_url = "https://api.open-meteo.com/v1/forecast"
        weather_params = {
            "latitude": latitude,
            "longitude": longitude,
            "current": "temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m",
            "temperature_unit": "fahrenheit"
        }
        
        weather_response = requests.get(weather_url, params=weather_params, timeout=5)
        weather_data = weather_response.json()
        
        if "current" not in weather_data:
            return "Unable to fetch weather data at this time."
        
        current = weather_data["current"]
        
        # Transform data to natural language
        temp = current["temperature_2m"]
        humidity = current["relative_humidity_2m"]
        wind_speed = current["wind_speed_10m"]
        
        # Simple weather code interpretation
        weather_codes = {
            0: "clear sky",
            1: "mostly clear",
            2: "partly cloudy",
            3: "overcast",
            45: "foggy",
            48: "foggy with rime",
            51: "light drizzle",
            53: "moderate drizzle",
            55: "dense drizzle",
            61: "slight rain",
            63: "moderate rain",
            65: "heavy rain",
            71: "slight snow",
            73: "moderate snow",
            75: "heavy snow",
            80: "rain showers",
            81: "moderate rain showers",
            82: "violent rain showers",
            85: "snow showers",
            86: "heavy snow showers",
            95: "thunderstorm",
            96: "thunderstorm with hail",
            99: "severe thunderstorm"
        }
        
        weather_description = weather_codes.get(current["weather_code"], "unknown conditions")
        
        response = f"🌍 Weather in {name}{', ' + country if country else ''}:\n"
        response += f"Temperature: {temp}°F\n"
        response += f"Conditions: {weather_description.capitalize()}\n"
        response += f"Humidity: {humidity}%\n"
        response += f"Wind Speed: {wind_speed} mph"
        
        return response
        
    except requests.Timeout:
        return "Weather service request timed out. Please try again."
    except Exception as e:
        return f"Unable to fetch weather data: {str(e)}"


# ==================== SERVICE 2: SEMANTIC SEARCH ====================
# Knowledge base data
KNOWLEDGE_BASE = {
    "python": "Python is a high-level programming language known for its simplicity and readability. It uses indentation to define code blocks.",
    "ml": "Machine learning is a subset of artificial intelligence that focuses on enabling computers to learn from data without being explicitly programmed.",
    "nlp": "Natural language processing (NLP) is a field of AI that deals with the interaction between computers and human language.",
    "data_science": "Data science combines statistics, mathematics, programming, and domain knowledge to extract insights from data.",
    "deep_learning": "Deep learning uses neural networks with multiple layers to learn complex patterns in data.",
    "vectordb": "A vector database stores and retrieves data based on vector embeddings, enabling semantic search capabilities.",
    "rag": "Retrieval-augmented generation (RAG) combines retrieval and generation to provide more accurate and contextual responses.",
    "embeddings": "Embeddings are numerical representations of text that capture semantic meaning, often generated by neural networks.",
    "finetuning": "Fine-tuning adapts pre-trained models to specific tasks by training them on domain-specific data.",
    "prompting": "Prompt engineering involves crafting effective instructions to guide AI models toward desired outputs."
}


def _simple_similarity(query: str, text: str) -> float:
    """
    Calculate simple text similarity based on keyword overlap.
    
    Args:
        query: User's query
        text: Document text
        
    Returns:
        Similarity score 0-1
    """
    query_words = set(query.lower().split())
    text_words = set(text.lower().split())
    
    if not query_words or not text_words:
        return 0.0
    
    intersection = len(query_words & text_words)
    union = len(query_words | text_words)
    
    return intersection / union if union > 0 else 0.0


@tool
def search_knowledge_base(query: str) -> str:
    """
    Search the knowledge base for information about AI, data science, and technology.
    
    Args:
        query: Search query (e.g., "machine learning", "embeddings", "RAG")
    
    Returns:
        Top 3 most relevant results from the knowledge base
    """
    try:
        # Calculate similarity for each document
        results = []
        for key, text in KNOWLEDGE_BASE.items():
            similarity = _simple_similarity(query, text)
            if similarity > 0:
                results.append((text, similarity, key))
        
        # Sort by similarity (highest first)
        results.sort(key=lambda x: x[1], reverse=True)
        
        if not results:
            return "No relevant information found in the knowledge base for your query."
        
        # Return top 3 results
        response = "📚 Knowledge Base Results:\n\n"
        for i, (text, similarity, key) in enumerate(results[:3], 1):
            relevance = similarity * 100
            response += f"{i}. {text}\n   (Relevance: {relevance:.0f}%)\n\n"
        
        return response.strip()
        
    except Exception as e:
        return f"Error searching knowledge base: {str(e)}"


# ==================== SERVICE 3: TOOLS & CALCULATIONS ====================
@tool
def calculate_statistics(numbers: list) -> str:
    """
    Calculate basic statistics on a list of numbers.
    
    Args:
        numbers: List of numbers to analyze
    
    Returns:
        Statistics including count, sum, average, min, and max
    """
    if not numbers:
        return "Error: No numbers provided"
    
    stats = {
        "count": len(numbers),
        "sum": sum(numbers),
        "average": sum(numbers) / len(numbers),
        "min": min(numbers),
        "max": max(numbers)
    }
    
    return f"📊 Statistics:\n{json.dumps(stats, indent=2)}"


@tool
def convert_temperature(value: float, from_unit: str, to_unit: str) -> str:
    """
    Convert temperature between Celsius, Fahrenheit, and Kelvin.
    
    Args:
        value: Temperature value to convert
        from_unit: Source unit (C, F, or K)
        to_unit: Target unit (C, F, or K)
    
    Returns:
        Converted temperature value
    """
    try:
        # Convert to Celsius first
        if from_unit.upper() == "F":
            celsius = (value - 32) * 5 / 9
        elif from_unit.upper() == "K":
            celsius = value - 273.15
        else:
            celsius = value
        
        # Convert from Celsius to target unit
        if to_unit.upper() == "F":
            result = celsius * 9 / 5 + 32
        elif to_unit.upper() == "K":
            result = celsius + 273.15
        else:
            result = celsius
        
        return f"🌡️ Temperature Conversion: {value} {from_unit.upper()} → {result:.2f} {to_unit.upper()}"
    except Exception as e:
        return f"Error converting temperature: {str(e)}"


@tool
def generate_random_fact() -> str:
    """
    Generate a random interesting fact.
    
    Returns:
        A random fact string
    """
    facts = [
        "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that is still edible.",
        "A group of flamingos is called a 'flamboyance'.",
        "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
        "Octopuses have three hearts and blue blood.",
        "A day on Venus is longer than its year.",
        "The smell of fresh-cut grass is actually a plant defense mechanism.",
        "Coffee is the second most traded commodity in the world, after crude oil.",
        "Bananas are berries, but strawberries aren't.",
        "The human brain uses 20% of the body's energy despite being only 2% of body weight.",
        "A group of owls is called a 'parliament'."
    ]
    import random
    fact = random.choice(facts)
    return f"🎯 Fun Fact: {fact}"
